version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:5055
    volumes:
      - .:/code
    ports:
      - "5055:5055"
    depends_on:
      - db

